--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kaidomc-pm-pl/RegionProtect
build-by-default: true
branches:
- master
- temp
projects:
  RegionProtect:
    path: ""
    lint:
      phpstan: false
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: 2.1.0
...
