---
name: RegionProtect
version: 1.1.0
api: 4.0.0
main: kaidoMC\RegionProtect\RegionProtect
author: kaidoMC
description: A plugin that allows you to manage certain events in certain regions of the world.
website: https://github.com/kaidomc-pm-pl

commands:
  region:
    description: "Region property little feature!"
    permission: regionprotect.command.use
permissions:
  regionprotect.command.use:
    default: op
    description: "Basic permission to be able to use the Region feature"
  regionprotect.interactive.use:
    default: op
    description: "Permission is allowed to interact in the forbidden region. (Developing)"
...
